[package]
name = "Leonhard"
version = "0.1.0"
authors = ["screwdriver_ <luc14860@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
